/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Arboles.AVL;
import Arboles.ArbolB;
import Arboles.ArbolBinarioBusqueda;
import Arboles.ArbolMViasBusqueda;
import Arboles.CargarSintomas;
import Arboles.IArbolBusqueda;
import Excepciones.ClaveNoEncontrada;
import Excepciones.NoHayLaClave;
import Excepciones.OrdenInvalidoExcepcion;
import java.awt.Graphics;
import java.awt.Image;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JFrame;
/*---------------------------------*/


import javax.swing.JOptionPane;

public class Sintomas extends javax.swing.JFrame {
    
    IArbolBusqueda<String, String> arbolPrueba;
    //---------------------------------------------------
//    private javax.swing.JRadioButton rbArbolBinario;
//    private javax.swing.JRadioButton rbAVL;
//    private javax.swing.JRadioButton rbArbolMVias;
//    private javax.swing.JRadioButton rbArbolB;
//    private javax.swing.ButtonGroup bgArboles;
    /**
     * Creates new form Agenda
     */
    
    
    public Sintomas() {
        initComponents();
        //this.setContentPane(fondoImagen);
        setResizable(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        rbArbolBinario = new javax.swing.JRadioButton();
        rbAVL = new javax.swing.JRadioButton();
        rbArbolB = new javax.swing.JRadioButton();
        rbArbolMVias = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sintomas de las enfermedades");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 610, 70));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 330, 40));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 330, 70));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton1.setText("Iniciar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 430, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Buscar sintoma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 230, 50));

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Insertar datos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 200, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del sintoma:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, 30));

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Eliminar sintoma");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 230, 50));

        rbArbolBinario.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        rbArbolBinario.setForeground(new java.awt.Color(0, 0, 0));
        rbArbolBinario.setText("ABB");
        rbArbolBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbArbolBinarioActionPerformed(evt);
            }
        });
        jPanel1.add(rbArbolBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, 20));

        rbAVL.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        rbAVL.setForeground(new java.awt.Color(0, 0, 0));
        rbAVL.setText("AVL");
        jPanel1.add(rbAVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 70, 20));

        rbArbolB.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        rbArbolB.setForeground(new java.awt.Color(0, 0, 0));
        rbArbolB.setText("AMV-B");
        rbArbolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbArbolBActionPerformed(evt);
            }
        });
        jPanel1.add(rbArbolB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, 40));

        rbArbolMVias.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        rbArbolMVias.setForeground(new java.awt.Color(0, 0, 0));
        rbArbolMVias.setText("AMV");
        jPanel1.add(rbArbolMVias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 70, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formulario/image5.jpg"))); // NOI18N
        jLabel1.setText("agebda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String arbolToString(IArbolBusqueda<String, String> arbol) {
        // Aquí debes implementar la lógica para convertir el árbol a una representación de cadena.
        // Este es un ejemplo simple que debes adaptar según tu implementación del árbol.
        StringBuilder sb = new StringBuilder();
        for (String clave : arbol.recorridoEnInOrden()) {
            sb.append(clave).append(": ").append(arbol.buscar(clave)).append("\n");
        }
        return sb.toString();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       	CargarSintomas nuevoArbol = new CargarSintomas(arbolPrueba);
	String clave = jTextField1.getText();
        String valor = jTextField2.getText();
        arbolPrueba.insertar(clave, valor);
        System.out.println(arbolPrueba);
        JOptionPane.showMessageDialog(null, "Contacto agregado correctamente...");

        // Actualizar el JTextArea con la representación del árbol
        jTextArea1.setText(arbolToString(arbolPrueba));
	System.out.println("---------------------------------------------------------------------------");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JOptionPane.showMessageDialog(null, "Sistema iniciado...");  
        if (rbArbolBinario.isSelected()) {
            arbolPrueba = new ArbolBinarioBusqueda<>();
        } else if (rbAVL.isSelected()) {
            arbolPrueba = new AVL<>();
        } else if (rbArbolMVias.isSelected()) {
            int orden = Integer.parseInt(JOptionPane.showInputDialog("Digite el orden para árbol MVias"));
            try {
                arbolPrueba = new ArbolMViasBusqueda<>(orden);
            } catch (OrdenInvalidoExcepcion ex) {
                Logger.getLogger(Sintomas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (rbArbolB.isSelected()) {
            try {
                arbolPrueba = new ArbolB<>(3);
            } catch (OrdenInvalidoExcepcion ex) {
                Logger.getLogger(Sintomas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String clave = (JOptionPane.showInputDialog("Ingrese el nombre de sintoma"));
            String valor = arbolPrueba.buscar(clave);
            JOptionPane.showMessageDialog(null, "Nombre del sintoma: " + valor);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbArbolBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbArbolBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbArbolBinarioActionPerformed

    private void rbArbolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbArbolBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbArbolBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String clave = JOptionPane.showInputDialog("Ingrese el nombre de sintoma");
	    try {
                    arbolPrueba.eliminar(clave);
		    //jTextArea1.setText(arbolPrueba.eliminar(clave));
		    JOptionPane.showMessageDialog(null, "Eliminado correctamente...");
		    System.out.println(arbolPrueba);
                    jTextArea1.setText(arbolToString(arbolPrueba));
		    System.out.println("-----------------------------------------------------------------------------------------");
	    } catch (NoHayLaClave ex) {
		    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
	    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        Inicio ventana2 = new Inicio();
        ventana2.setVisible(true);

        // Crear e instanciar Ventana1
        Sintomas ventana1 = new Sintomas();
        ventana1.setVisible(false);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Sintomas().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rbAVL;
    private javax.swing.JRadioButton rbArbolB;
    private javax.swing.JRadioButton rbArbolBinario;
    private javax.swing.JRadioButton rbArbolMVias;
    // End of variables declaration//GEN-END:variables

    
    
}